### ISSUE TITLE
No Broker Available 

### ISSUE THREAD

**Issue by Deanozk** [tosbala/flink-statefun-bookstore#1]
I am trying to run this excellent example on an M1 and everything deploys but I get error message:

 ✔ Container flink-statefun-bookstore-producer-1          Created                                                    0.0s 
Attaching to producer-1
producer-1  | Traceback (most recent call last):
producer-1  |   File "/app/producer.py", line 40, in <module>
producer-1  |     place_orders(book_list=book_list, no_of_orders=25)
producer-1  |   File "/app/producer.py", line 25, in place_orders
producer-1  |     producer = KafkaProducer(bootstrap_servers=['kafka:9092'])
producer-1  |   File "/usr/local/lib/python3.9/site-packages/kafka/producer/kafka.py", line 381, in __init__
producer-1  |     client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
producer-1  |   File "/usr/local/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
producer-1  |     self.config['api_version'] = self.check_version(timeout=check_timeout)
producer-1  |   File "/usr/local/lib/python3.9/site-packages/kafka/client_async.py", line 927, in check_version
producer-1  |     raise Errors.NoBrokersAvailable()
producer-1  | kafka.errors.NoBrokersAvailable: NoBrokersAvailable
producer-1 exited with code 1

**Comment by Deanozk** [comment]
![Uploading Screenshot 2024-02-14 at 00.14.48.png…]()
